CREATE TABLE IF NOT EXISTS user_dashboard_config (
  user_id    UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  widgets    JSONB NOT NULL DEFAULT '[]',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
